FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# VSE_2018-11-12-REST-API-BP

Polls is a simple API allowing consumers to view polls and vote in them.

## User [/user/{username}]

+ Parameters
    + username

+ Attributes
    + username: Kyle (required)
    + email: `kyle@apiary.io` (required)


## Questions Collection [/questions]

### Get all questions [GET]

+ Request (application/json)
    + Attributes (User)

+ Response 200 (application/json)

    + Body
    
            {
                q: "",
                r: [{
                        "i": "java",
                        "p": 123
                    }]
            }
            

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "aaa": {?question}
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }